---
title: "R Notebook for OCD4 Analysis"
output: html_notebook
---

This script focuses on the analysis of OCD4 data for submission to the JAMA network open journal.

```{r}
# Loading necessary libraries
library('readxl')
library('forecast')
library('dplyr')
# Setting the working directory and reading the dataset
setwd("~/Dropbox/gitLab/studyDepressionBigData")
DTPANIC <- read_xlsx("PanicWholePopu.xlsx", sheet = "PANIC")
mTotPopulation = DTPANIC$totN1

# Reading OCD4 data
DTOCD <- read_xlsx("PanicWholePopu.xlsx", sheet = "OCD")

# Calculating prevalence and incidence rates for OCD4
nPrevOCD4 = DTOCD$prevN4 / mTotPopulation * 100
nNPrevOCD4 = DTOCD$inciN4 / mTotPopulation * 100
# Creating a dataframe with the collected information
data <- data.frame(
  month = as.Date(DTPANIC$DateColumn),
  prevOCD4 = nPrevOCD4,
  inciOCD4 = nNPrevOCD4
)

# Converting the date to a time series object
prevOCD4.ts = ts(data$prevOCD4, frequency = 12, start = c(2004,1))
inciOCD4.ts = ts(data$inciOCD4, frequency = 12, start = c(2004,1))
# Plotting the time series data
plot(prevOCD4.ts, type="l", col="blue", xlab="Year", ylab="Prevalence", main="Prevalence of OCD4 Over Time")
# Statistical analysis for OCD4 incidence
modelOCD4 <- auto.arima(inciOCD4.ts, seasonal=TRUE)
summary(modelOCD4)
